dist: bionic

language: go
go:
  - "1.16"
  - master

install:
  - go get -v -t -d ./...

script:
  - go test -race -coverprofile=multidb.out -covermode=atomic

after_script:
  - bash <(curl -s https://codecov.io/bash) -f '*.out'
