// Copyright (c) 2021, Mohlmann Solutions SRL. All rights reserved.
// Use of this source code is governed by a License that can be found in the LICENSE file.
// SPDX-License-Identifier: BSD-3-Clause

// Definitions for testing.
// Generate with:
// protoc --go_out=. --go_opt=paths=source_relative bind_test.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: bind_test.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Toggle  bool              `protobuf:"varint,1,opt,name=toggle,proto3" json:"toggle,omitempty"`
	Number  int32             `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Snumber int32             `protobuf:"zigzag32,3,opt,name=snumber,proto3" json:"snumber,omitempty"`
	Unumber uint32            `protobuf:"varint,4,opt,name=unumber,proto3" json:"unumber,omitempty"`
	Large   int64             `protobuf:"varint,5,opt,name=large,proto3" json:"large,omitempty"`
	Slarge  int64             `protobuf:"fixed64,6,opt,name=slarge,proto3" json:"slarge,omitempty"`
	Ularge  uint64            `protobuf:"fixed64,7,opt,name=ularge,proto3" json:"ularge,omitempty"`
	Sfloat  float32           `protobuf:"fixed32,8,opt,name=sfloat,proto3" json:"sfloat,omitempty"`
	Lfloat  float64           `protobuf:"fixed64,9,opt,name=lfloat,proto3" json:"lfloat,omitempty"`
	Text    string            `protobuf:"bytes,10,opt,name=text,proto3" json:"text,omitempty"`
	Bin     []byte            `protobuf:"bytes,11,opt,name=bin,proto3" json:"bin,omitempty"`
	Mp      map[string]string `protobuf:"bytes,12,rep,name=mp,proto3" json:"mp,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // Scanning not supported
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bind_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_bind_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_bind_test_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetToggle() bool {
	if x != nil {
		return x.Toggle
	}
	return false
}

func (x *Msg) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Msg) GetSnumber() int32 {
	if x != nil {
		return x.Snumber
	}
	return 0
}

func (x *Msg) GetUnumber() uint32 {
	if x != nil {
		return x.Unumber
	}
	return 0
}

func (x *Msg) GetLarge() int64 {
	if x != nil {
		return x.Large
	}
	return 0
}

func (x *Msg) GetSlarge() int64 {
	if x != nil {
		return x.Slarge
	}
	return 0
}

func (x *Msg) GetUlarge() uint64 {
	if x != nil {
		return x.Ularge
	}
	return 0
}

func (x *Msg) GetSfloat() float32 {
	if x != nil {
		return x.Sfloat
	}
	return 0
}

func (x *Msg) GetLfloat() float64 {
	if x != nil {
		return x.Lfloat
	}
	return 0
}

func (x *Msg) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Msg) GetBin() []byte {
	if x != nil {
		return x.Bin
	}
	return nil
}

func (x *Msg) GetMp() map[string]string {
	if x != nil {
		return x.Mp
	}
	return nil
}

var File_bind_test_proto protoreflect.FileDescriptor

var file_bind_test_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x62, 0x69, 0x6e, 0x64, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xdd, 0x02, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x74,
	0x6f, 0x67, 0x67, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x11, 0x52, 0x07,
	0x73, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x75, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6c, 0x61, 0x72, 0x67,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x10, 0x52, 0x06, 0x73, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x06, 0x52,
	0x06, 0x75, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x66, 0x6c, 0x6f, 0x61,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x73, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x6c, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x62,
	0x69, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x62, 0x69, 0x6e, 0x12, 0x1f, 0x0a,
	0x02, 0x6d, 0x70, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4d,
	0x73, 0x67, 0x2e, 0x4d, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x02, 0x6d, 0x70, 0x1a, 0x35,
	0x0a, 0x07, 0x4d, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x70, 0x62, 0x69, 0x6e, 0x64,
	0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bind_test_proto_rawDescOnce sync.Once
	file_bind_test_proto_rawDescData = file_bind_test_proto_rawDesc
)

func file_bind_test_proto_rawDescGZIP() []byte {
	file_bind_test_proto_rawDescOnce.Do(func() {
		file_bind_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_bind_test_proto_rawDescData)
	})
	return file_bind_test_proto_rawDescData
}

var file_bind_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bind_test_proto_goTypes = []interface{}{
	(*Msg)(nil), // 0: pb.Msg
	nil,         // 1: pb.Msg.MpEntry
}
var file_bind_test_proto_depIdxs = []int32{
	1, // 0: pb.Msg.mp:type_name -> pb.Msg.MpEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bind_test_proto_init() }
func file_bind_test_proto_init() {
	if File_bind_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bind_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bind_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bind_test_proto_goTypes,
		DependencyIndexes: file_bind_test_proto_depIdxs,
		MessageInfos:      file_bind_test_proto_msgTypes,
	}.Build()
	File_bind_test_proto = out.File
	file_bind_test_proto_rawDesc = nil
	file_bind_test_proto_goTypes = nil
	file_bind_test_proto_depIdxs = nil
}
